#version: "1"
#
#services:
#  # 给SpringBoot起一个自定义的服务名
#  demo:
#    # 将来 Dockerfile 构建的镜像名及版本号
#    image: demo:1.0
#    # 指定容器名称
#    container_name: demo
#    # 开放端口
#    ports:
#      - "8081:8081"
#    # 配置容器连接的自定义网络，跟mysql、redis 属于同一个网络
#    networks:
#      - app_net
#    # 容器启动时依赖于以下服务
#    depends_on:
#      - redisServer
#      - mysqlServer
#  # mysql服务
#  mysqlServer:
#    image: mysql:8.0.33
#    ports:
#      - "3306:3306"
#    #volumes:
#    #  - /mydocker/mysql/data:/var/lib/mysql
#    #  - /mydocker/mysql/conf.d:/etc/mysql/conf.d
#    environment:
#      MYSQL_ROOT_PASSWORD: '123456'
#    networks:
#      - app_net
#  # redis 服务
#  redisServer:
#    image: redis:7.0.11
#    ports:
#      - "6379:6379"
#    #volumes:
#    #  - /mydocker/redis/data:/data
#    #  - /mydocker/redis/redis.conf:/usr/local/etc/redis/redis.conf
#    networks:
#      - app_net
#    command: redis-server
#  # nginx 服务
#  #nginxServer:
#    #image: nginx:1.22
#    #volumes:
#    #  - /mydocker/nginx/nginx.conf:/etc/nginx/nginx.conf
#    #  - /mydocker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#    #  - /mydocker/nginx/html:/usr/share/nginx/html
#    #ports:
#    #  - "8080:8080"
#    #networks:
#    #  - app_net
#networks:
#  app_net:
